### ISSUE TITLE
Support for MDLC items?

### ISSUE THREAD

**Issue by zpavic** [neutmute/nlog-targets-loggly#10]
We have some data as part of the NLog MDLC which is currently a part of a file logger layout. Ideally, we'd like to send this to Loggly to correlate log statements to a logical request. However, looking at the [LogglyTarget](https://github.com/neutmute/nlog-targets-loggly/blob/master/src/NLog.Targets.Loggly/LogglyTarget.cs) class, it seems that there is only support for passing in `LogEventInfo.Properties` into `LogglyEvent.Data`. For our uses, it would be ideal if the logger could incorporate this data without needing to alter each area we are logging.

Are there any thoughts on allowing MDLC properties to be passed in - either selectively or globally?

**Comment by neutmute** [comment]
Can't say I've heard about MDLC - happy to accept a PR

**Comment by zpavic** [comment]
In our scenario, we are attempting to enable full log capture with a correlation id to Loggly as part of our assessment of the tooling. This should apply to ASP.NET code such as modules/handlers as well as controller code. The [MappedDiagnosticLogicalContext](https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer) stores items as part of the logical CallContext - and this flows to other threads across async/await calls. However, in ASP.NET it is more problematic.

HttpModules can handle lifecycle events on different threads. This switching apparently does not preserve the logical context. The NLog maintainers recommend using the HttpContext.Items to store data and reference with [${aspnet-item}](https://github.com/NLog/NLog/wiki/AspNetItem-layout-renderer) but this doesn't seem to flow across async/await calls. So we are forced with the prospect of having logging with the correlation id for some areas of the code and not others which ever option is selected. We'd need a good solution to this problem before spending some effort enhancing the logger.

**Comment by snakefoot** [comment]
@neutmute If we can upgrade from NLog 2.1 to NLog 4.5 (Already used for NetCore). Then one can inherit from `NLog.Targets.TargetWithContext` instead of `NLog.Targets.TargetWithLayout` and it will have support for capture of MDLC: https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer

**Comment by neutmute** [comment]
Thanks @snakefoot , happy to update to 4.5 if someone wants to PR

**Comment by snakefoot** [comment]
@neutmute Created #20 that resolves this issue

**Comment by neutmute** [comment]
Thanks snakefoot!
