### ISSUE TITLE
System.MissingMethodException when logging via Nlog

### ISSUE THREAD

**Issue by trentstollery** [neutmute/nlog-targets-loggly#24]
Hey!
Just trying to setup up loggly via Nlog and I keep getting this exception.
Seems to be related to a missing method but I can't seem to place it.
I don't know if it's a config issues but my config is basically the same as your example(I'm using in code config and the standard nlog config file).
I'm setting this up in a console app using .net core 2.2
Let me know if you need anything!
`2019-09-05 14:15:02.9569 Error Error has been raised. Exception: System.MissingMethodException: Method not found: 'Void Loggly.LogglyException.Throw(System.String, System.Object[])'.
   at NLog.Targets.LogglyTarget.ToSyslogLevel(LogLevel nLogLevel)
   at NLog.Targets.LogglyTarget.ConvertToLogglyEvent(LogEventInfo logEvent)
   at NLog.Targets.LogglyTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)`

**Comment by neutmute** [comment]
hmm - I think I remember merging a PR that removed that exception. Perhaps the NLog target is still expecting it. 
I don't use this library anymore so happy to accept a PR to fix but I won't be putting any time in myself. Trust you understand.

**Comment by snakefoot** [comment]
Created #25 to resolve this issue.

**Comment by snakefoot** [comment]
Nuget released: https://www.nuget.org/packages/NLog.Targets.Loggly/4.8.10
