### ISSUE TITLE
Deadlock when inside LogglyTarget.Write

### ISSUE THREAD

**Issue by xdansmith** [neutmute/nlog-targets-loggly#33]
I just upgraded to the latest version of this library (4.8.26) via NuGet; I was using version 4.5.2.5 previously.

Since upgrading, when used in an environment where hundreds of concurrent calls are happening, we're now experiencing significant delays. Running a memory dump against a process where this happened, it revealed that the lock that was blocking other threads was coming from in `NLog.Targets.LogglyTarget.Write(LogEventInfo)`

Stack trace from memory dump: 
```
[[GCFrame]]
--
[[HelperMethodFrame_1OBJ] (System.Threading.Monitor.ObjWait)] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)+348
System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)+bb
System.Threading.Tasks.Task.InternalWait(Int32, System.Threading.CancellationToken)+1a1
System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)+3f
NLog.Targets.LogglyTarget.Write(NLog.LogEventInfo)+6e
NLog.Targets.Target.Write(NLog.Common.AsyncLogEventInfo)+30
NLog.Targets.Target.WriteAsyncThreadSafe(NLog.Common.AsyncLogEventInfo)+8b
NLog.Targets.Target.WriteAsyncLogEvent(NLog.Common.AsyncLogEventInfo)+11e
NLog.LoggerImpl.WriteToTargetWithFilterChain(NLog.Targets.Target, NLog.Filters.FilterResult, NLog.LogEventInfo, NLog.Common.AsyncContinuation)+92
NLog.LoggerImpl.Write(System.Type, NLog.Internal.TargetWithFilterChain, NLog.LogEventInfo, NLog.LogFactory)+194
NLog.Logger.Log(NLog.LogEventInfo)+57
```

Has anyone else experienced this? For now I'm downgrading back to the previous version but I'm hoping a fix can be found or maybe I can help create one.

Thank you!

**Comment by neutmute** [comment]
Hi Dan - I don't use the library any more. If you come up with a fix - happy to receive the PR

**Comment by snakefoot** [comment]
@neutmute Created #34 for resolving this issue.

**Comment by neutmute** [comment]
Love your work @snakefoot !

**Comment by snakefoot** [comment]
> @neutmute Love your work @snakefoot !

The Loggly target was part of the inspiratation for AsyncTaskTarget, so the cycle is complete.

**Comment by snakefoot** [comment]
@xdansmith Please try [NLog.Targets.Loggly ver. 4.8.38](https://www.nuget.org/packages/NLog.Targets.Loggly/4.8.38) to see if it solves the problem.
