### ISSUE TITLE
Incorrect Nuget Install-Package reference

### ISSUE THREAD

**Issue by ShaneCourtrille** [neutmute/nlog-targets-loggly#7]
There was no Install-Package NLog-Targets-Loggly package registered with nuget.org.  There is a NLog.Targets.Loggly though

**Comment by neutmute** [comment]
Hi Shane - I don't quite understand the problem? 
Package is available @ https://www.nuget.org/packages/NLog.Targets.Loggly/

**Comment by ShaneCourtrille** [comment]
The github page https://github.com/neutmute/nlog-targets-loggly says
NLog-targets-loggly

**Comment by neutmute** [comment]
ah. dots vs dashes. now I see. fixed - thanks!
