### ISSUE TITLE
How to add ActivityID to messages sent to Loggly

### ISSUE THREAD

**Issue by rajinders** [neutmute/nlog-targets-loggly#8]
I am trying to add "ActivityID" to each message sent to Loggly. I want to be able to search based on this message so I can find all the transactions for that particular ActivityID.

Here is how I create the NLog event.

LogEventInfo le = new LogEventInfo();
                le.Level = LogLevel.Info;
                le.LoggerName = "Console.Main";
                le.Properties["ActivityID"] = 999;
                le.Message = "This is an debug about from NLog to Loggly";
                log.Info(le);

Here I define a layout where I extract the value of "ActivityID" from teh event-context
<variable name="DefaultLayout" value="${longdate} | ${event-context:item=ActivityID} | ${level:uppercase=true:padding=5} | ${message} | ${exception:format=type,tostring}" />

    <targets async="true">
      <target name="ColorConsole" xsi:type="ColoredConsole" layout="${DefaultLayout}" />
      <target name="Loggly" xsi:type="Loggly" layout="${DefaultLayout}" />
    </targets>
    <rules>
      <logger name="*" minlevel="Debug" writeTo="ColorConsole,Loggly" />
    </rules>

The message renders as expected on the Console but in Loggly I don't see the ActivityID anywhere.
It seems to me that custom properties in the logEvent are not passed to Loggly.

I was wondering if there is a better way to do what I am trying to do.

Thanks

**Comment by neutmute** [comment]
Hi there - Try running the example code to see if it works for you
https://github.com/neutmute/nlog-targets-loggly/blob/master/src/Demo/Program.cs
You need to wire in your account details.
Only syntax I see that is different is the Properties.Add is used in the sample.
Also try using Fiddler to confirm the property you are adding is sent over the wire to Loggly

**Comment by rajinders** [comment]
I looked at the code sample above there was one minor difference. 
I used Properties.Add and everything is working as expected.

Close this issue.

Thanks
